variables:
  
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '190aab04-bf23-42ec-942f-494f6d6f6710'
  imageRepository: 'mspreagendamiento'
  containerRegistry: 'preagendamiento.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'preagendamiento210949f5-auth'

apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mspreagendamiento 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mspreagendamiento 
    spec:
      containers:
        - name: mspreagendamiento 
          image: preagendamiento.azurecr.io/mspreagendamiento::$(tag)
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: mspreagendamiento
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: mspreagendamiento