apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mspreagendamiento 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mspreagendamiento 
    spec:
      containers:
        - name: mspreagendamiento 
          image: preagendamiento.azurecr.io/mspreagendamiento
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: preagendamiento-generated-image-pull-secret
