apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mspreagendamiento 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mspreagendamiento 
    spec:
      containers:
        - name: mspreagendamiento 
          image: preagendamiento.azurecr.io/mspreagendamiento:latest
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: mspreagendamiento
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: mspreagendamiento